export const TOGGLE_SORT_AND_FILTER = "TOGGLE_SORT_AND_FILTER";
export const SET_SORTING_CRITERION = "SET_SORTING_CRITERION";
export const SET_FILTERING = "SET_FILTERING";
export const SET_SORTING_ASCENDING = "SET_SORTING_ASCENDING";
export const SET_SELECTED_ESTABLISHMENT = "SET_SELECTED_ESTABLISHMENT";
export const SET_SHOWINFO = "SET_SHOWINFO";
